### ISSUE TITLE
Image missing from Fly config on Dashboard

### ISSUE THREAD

**Issue by oscarhermoso** [andrewbaxter/terraform-provider-fly#12]
## Steps to reproduce

Given Terraform like below:

```hcl
resource "fly_machine" "app" {
  for_each = var.machine_names
  
  app    = "exampleapp"
  name   = each.key
  region = "syd"

  cpus     = var.cpus
  memory   = var.memory_mb
  image    = "supabase/stripe-sync-engine"
  env      = var.env
  services = var.services
  cmd      = var.cmd
}

```

## Expected

Expect that after deployment, the build is included in the Configuration shown on the dashboard 

```toml
app = "exampleapp"

[build]
  image = "supabase/stripe-sync-engine"

[env]
AUTO_EXPAND_LISTS = "true"
PORT = "8080"

[[metrics]]

[[services]]
internal_port = 8_080
protocol = "tcp"

  [[services.ports]]
  handlers = [ "http" ]
  port = 80

  [[services.ports]]
  handlers = [ "tls", "http" ]
  port = 443
```

## Actual

Build is missing from the output

```diff
app = "exampleapp"

- [build]
-   image = "supabase/stripe-sync-engine"

[env]
AUTO_EXPAND_LISTS = "true"
PORT = "8080"

[[metrics]]

[[services]]
internal_port = 8_080
protocol = "tcp"

  [[services.ports]]
  handlers = [ "http" ]
  port = 80

  [[services.ports]]
  handlers = [ "tls", "http" ]
  port = 443
```

This causes following issues if you try to issue a `fly deploy` command from the CLI without a `fly.toml`

![Screenshot from 2024-11-29 13-14-26](https://github.com/user-attachments/assets/c7362d84-261c-446b-8a68-7cdee447cf7c)

```sh
fly deploy -a exampleapp
==> Verifying app config
Validating --config path unset--
✓ Configuration is valid
--> Verified app config
==> Building image
==> Building image
Error: failed to fetch an image or build from source: app does not have a Dockerfile or buildpacks configured. See https://fly.io/docs/reference/configuration/#the-build-section
```

I believe this is caused by the fact that image is specified at the top level - but it actually needs to be defined within build:

https://github.com/andrewbaxter/terraform-provider-fly/blob/bf858c979e73627cb1c22c0d10461e6d211d0b92/machineapi/machines.go#L81-L91

https://fly.io/docs/reference/configuration/#specify-a-docker-image

I imagine this used to work but Fly changed the API at some point in time.
